name: snake
dependencies:
- anaconda-client=1.2.2=py35_0
- bioconductor-deseq2=1.10.0=r3.2.2_1
- biopython=1.66=np110py35_0
- docutils=0.12=py35_0
- get_terminal_size=1.0.0=py35_0
- gffutils=0.8.7.1=py35_0
- ipython=4.2.0=py35_0
- jedi=0.9.0=py35_0
- jinja2=2.8=py35_0
- jupyter=1.0.0=py35_2
- matplotlib=1.5.1=np110py35_0
- networkx=1.11=py35_0
- numpy=1.10.4=py35_0
- pandas=0.17.1=np110py35_0
- pytables=3.2.2=np110py35_0
- python=3.5.1=0
- pyyaml=3.11=py35_1
- rpy2=2.7.6=py35r3.2.2_0
- scikit-learn=0.17=np110py35_2
- scipy=0.17.0
- setuptools=19.6.2=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- yaml=0.1.6=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - greenlet==0.4.9
  - ipdb==0.9.0
  - neovim==0.1.5
  - snakemake==3.6.0
  - sphinx-rtd-theme==0.1.9
  - tables==3.2.2
