#!/bin/bash

#PBS -N smk

SNAKEFILE=$1
EXTRA=$2

snakemake \
    -p \
    --rerun-incomplete \
    --jobname "s.{rulename}.{jobid}.sh" \
    -j 999 \
    --verbose \
    --cluster-config slurm_cluster_config.yaml \
    --cluster "sbatch --cpus-per-task {threads} --mem {cluster.mem} --time {cluster.time} --output=slurm_logs/$EXTRA.%j --error=slurm_logs/$EXTRA.%j" \
    --latency-wait=60 \
    -s $SNAKEFILE \
    $EXTRA \
